services:
  postgres:
    image: postgres:16
    env_file:
      - env/backend.prod.env
    volumes:
      - postgresDb:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - env/backend.prod.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  postgresDb:
