services:
  postgres:
    image: postgres:latest
    env_file: .env.prod
    volumes:
      - postgresDb:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file: .env.prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  postgresDb:
