services:
  postgres:
    image: postgres:16
    container_name: home_recipes_postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"   # optional but useful for local psql
    volumes:
      - postgresDb:/var/lib/postgresql/data
    networks:
      - home-recipes-net

  redis:
    image: redis:7
    container_name: home_recipes_redis
    networks:
      - home-recipes-net

  mailhog:
    image: mailhog/mailhog
    container_name: home_recipes_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - home-recipes-net

  backend:
    container_name: home_recipes_backend_dev
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.dev
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
      - redis
      - mailhog
    networks:
      - home-recipes-net

volumes:
  postgresDb:

networks:
  home-recipes-net:
    driver: bridge