services:
  postgres:
    image: postgres:16
    env_file:
      - env/backend.docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgresDb:/var/lib/postgresql/data
    networks:
      - home-recipes-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    networks:
      - home-recipes-net

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - home-recipes-net

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.dev
    env_file:
      - env/backend.docker.env
    ports:
      - "8088:8088"   # backend
      - "2345:2345"   # debug port for gdbserver
    volumes:
      - ./backend:/usr/src/app
      - ./docker/backend/entrypoint.sh:/entrypoint.sh
      - ./backend/target:/usr/src/app/target
    command: >
      bash -c "cargo build && gdbserver :2345 target/debug/backend"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - home-recipes-net

volumes:
  postgresDb:

networks:
  home-recipes-net:
    driver: bridge
